function get_card_set(card_name){
    var card_set = {
        "Cellar" : "Base",
        "Chapel" : "Base",
        "Moat" : "Base",
        "Chancellor" : "Base",
        "Harbinger" : "Base",
        "Merchant" : "Base",
        "Village" : "Base",
        "Woodcutter" : "Base",
        "Workshop" : "Base",
        "Vassal" : "Base",
        "Bureaucrat" : "Base",
        "Feast" : "Base",
        "Gardens" : "Base",
        "Militia" : "Base",
        "Moneylender" : "Base",
        "Poacher" : "Base",
        "Remodel" : "Base",
        "Smithy" : "Base",
        "Spy" : "Base",
        "Thief" : "Base",
        "Throne Room" : "Base",
        "Bandit" : "Base",
        "Council Room" : "Base",
        "Festival" : "Base",
        "Laboratory" : "Base",
        "Library" : "Base",
        "Market" : "Base",
        "Mine" : "Base",
        "Sentry" : "Base",
        "Witch" : "Base",
        "Adventurer" : "Base",
        "Artisan" : "Base",
        "Copper" : "Base",
        "Silver" : "Base",
        "Gold" : "Base",
        "Estate" : "Base",
        "Duchy" : "Base",
        "Province" : "Base",
        "Curse" : "Base",
        "Courtyard" : "Intrigue",
        "Lurker" : "Intrigue",
        "Pawn" : "Intrigue",
        "Secret Chamber" : "Intrigue",
        "Great Hall" : "Intrigue",
        "Masquerade" : "Intrigue",
        "Shanty Town" : "Intrigue",
        "Steward" : "Intrigue",
        "Swindler" : "Intrigue",
        "Wishing Well" : "Intrigue",
        "Baron" : "Intrigue",
        "Bridge" : "Intrigue",
        "Conspirator" : "Intrigue",
        "Coppersmith" : "Intrigue",
        "Diplomat" : "Intrigue",
        "Ironworks" : "Intrigue",
        "Mill" : "Intrigue",
        "Mining Village" : "Intrigue",
        "Scout" : "Intrigue",
        "Secret Passage" : "Intrigue",
        "Courtier" : "Intrigue",
        "Duke" : "Intrigue",
        "Minion" : "Intrigue",
        "Patrol" : "Intrigue",
        "Replace" : "Intrigue",
        "Saboteur" : "Intrigue",
        "Torturer" : "Intrigue",
        "Trading Post" : "Intrigue",
        "Tribute" : "Intrigue",
        "Upgrade" : "Intrigue",
        "Harem" : "Intrigue",
        "Nobles" : "Intrigue",
        "Embargo" : "Seaside",
        "Haven" : "Seaside",
        "Lighthouse" : "Seaside",
        "Native Village" : "Seaside",
        "Pearl Diver" : "Seaside",
        "Ambassador" : "Seaside",
        "Fishing Village" : "Seaside",
        "Lookout" : "Seaside",
        "Smugglers" : "Seaside",
        "Warehouse" : "Seaside",
        "Caravan" : "Seaside",
        "Cutpurse" : "Seaside",
        "Island" : "Seaside",
        "Navigator" : "Seaside",
        "Pirate Ship" : "Seaside",
        "Salvager" : "Seaside",
        "Sea Hag" : "Seaside",
        "Treasure Map" : "Seaside",
        "Bazaar" : "Seaside",
        "Explorer" : "Seaside",
        "Ghost Ship" : "Seaside",
        "Merchant Ship" : "Seaside",
        "Outpost" : "Seaside",
        "Tactician" : "Seaside",
        "Treasury" : "Seaside",
        "Wharf" : "Seaside",
        "Herbalist" : "Alchemy",
        "Potion" : "Alchemy",
        "Apprentice" : "Alchemy",
        "Transmute" : "Alchemy",
        "Vineyard" : "Alchemy",
        "Apothecary" : "Alchemy",
        "Scrying Pool" : "Alchemy",
        "University" : "Alchemy",
        "Alchemist" : "Alchemy",
        "Familiar" : "Alchemy",
        "Philosopher's Stone" : "Alchemy",
        "Golem" : "Alchemy",
        "Possession" : "Alchemy",
        "Loan" : "Prosperity",
        "Trade Route" : "Prosperity",
        "Watchtower" : "Prosperity",
        "Bishop" : "Prosperity",
        "Monument" : "Prosperity",
        "Quarry" : "Prosperity",
        "Talisman" : "Prosperity",
        "Worker's Village" : "Prosperity",
        "City" : "Prosperity",
        "Contraband" : "Prosperity",
        "Counting House" : "Prosperity",
        "Mint" : "Prosperity",
        "Mountebank" : "Prosperity",
        "Rabble" : "Prosperity",
        "Royal Seal" : "Prosperity",
        "Vault" : "Prosperity",
        "Venture" : "Prosperity",
        "Goons" : "Prosperity",
        "Grand Market" : "Prosperity",
        "Hoard" : "Prosperity",
        "Bank" : "Prosperity",
        "Expand" : "Prosperity",
        "Forge" : "Prosperity",
        "King's Court" : "Prosperity",
        "Peddler" : "Prosperity",
        "Platinum" : "Prosperity",
        "Colony" : "Prosperity",
        "Hamlet" : "Cornucopia",
        "Fortune Teller" : "Cornucopia",
        "Menagerie" : "Cornucopia",
        "Farming Village" : "Cornucopia",
        "Horse Traders" : "Cornucopia",
        "Remake" : "Cornucopia",
        "Tournament" : "Cornucopia",
        "Young Witch" : "Cornucopia",
        "Harvest" : "Cornucopia",
        "Horn of Plenty" : "Cornucopia",
        "Hunting Party" : "Cornucopia",
        "Jester" : "Cornucopia",
        "Fairgrounds" : "Cornucopia",
        "Bag of Gold" : "Cornucopia",
        "Diadem" : "Cornucopia",
        "Followers" : "Cornucopia",
        "Princess" : "Cornucopia",
        "Trusty Steed" : "Cornucopia",
        "Crossroads" : "Hinterlands",
        "Duchess" : "Hinterlands",
        "Fool's Gold" : "Hinterlands",
        "Develop" : "Hinterlands",
        "Oasis" : "Hinterlands",
        "Oracle" : "Hinterlands",
        "Scheme" : "Hinterlands",
        "Tunnel" : "Hinterlands",
        "Jack of all Trades" : "Hinterlands",
        "Noble Brigand" : "Hinterlands",
        "Nomad Camp" : "Hinterlands",
        "Silk Road" : "Hinterlands",
        "Spice Merchant" : "Hinterlands",
        "Trader" : "Hinterlands",
        "Cache" : "Hinterlands",
        "Cartographer" : "Hinterlands",
        "Embassy" : "Hinterlands",
        "Haggler" : "Hinterlands",
        "Highway" : "Hinterlands",
        "Ill-Gotten Gains" : "Hinterlands",
        "Inn" : "Hinterlands",
        "Mandarin" : "Hinterlands",
        "Margrave" : "Hinterlands",
        "Stables" : "Hinterlands",
        "Border Village" : "Hinterlands",
        "Farmland" : "Hinterlands",
        "Madman" : "Dark Ages",
        "Mercenary" : "Dark Ages",
        "Spoils" : "Dark Ages",
        "Poor House" : "Dark Ages",
        "Beggar" : "Dark Ages",
        "Squire" : "Dark Ages",
        "Vagrant" : "Dark Ages",
        "Forager" : "Dark Ages",
        "Hermit" : "Dark Ages",
        "Market Square" : "Dark Ages",
        "Sage" : "Dark Ages",
        "Storeroom" : "Dark Ages",
        "Urchin" : "Dark Ages",
        "Armory" : "Dark Ages",
        "Death Cart" : "Dark Ages",
        "Feodum" : "Dark Ages",
        "Fortress" : "Dark Ages",
        "Ironmonger" : "Dark Ages",
        "Marauder" : "Dark Ages",
        "Procession" : "Dark Ages",
        "Rats" : "Dark Ages",
        "Scavenger" : "Dark Ages",
        "Wandering Minstrel" : "Dark Ages",
        "Band of Misfits" : "Dark Ages",
        "Bandit Camp" : "Dark Ages",
        "Catacombs" : "Dark Ages",
        "Count" : "Dark Ages",
        "Counterfeit" : "Dark Ages",
        "Cultist" : "Dark Ages",
        "Graverobber" : "Dark Ages",
        "Junk Dealer" : "Dark Ages",
        "Mystic" : "Dark Ages",
        "Pillage" : "Dark Ages",
        "Rebuild" : "Dark Ages",
        "Rogue" : "Dark Ages",
        "Altar" : "Dark Ages",
        "Hunting Grounds" : "Dark Ages",
        "Ruins" : "Dark Ages",
        "Abandoned Mine" : "Dark Ages",
        "Ruined Library" : "Dark Ages",
        "Ruined Market" : "Dark Ages",
        "Ruined Village" : "Dark Ages",
        "Survivors" : "Dark Ages",
        "Knights" : "Dark Ages",
        "Dame Anna" : "Dark Ages",
        "Dame Josephine" : "Dark Ages",
        "Dame Molly" : "Dark Ages",
        "Dame Natalie" : "Dark Ages",
        "Dame Sylvia" : "Dark Ages",
        "Sir Bailey" : "Dark Ages",
        "Sir Destry" : "Dark Ages",
        "Sir Martin" : "Dark Ages",
        "Sir Michael" : "Dark Ages",
        "Sir Vander" : "Dark Ages",
        "Shelters" : "Dark Ages",
        "Hovel" : "Dark Ages",
        "Necropolis" : "Dark Ages",
        "Overgrown Estate" : "Dark Ages",
        "Candlestick Maker" : "Guilds",
        "Stonemason" : "Guilds",
        "Doctor" : "Guilds",
        "Masterpiece" : "Guilds",
        "Advisor" : "Guilds",
        "Herald" : "Guilds",
        "Plaza" : "Guilds",
        "Taxman" : "Guilds",
        "Baker" : "Guilds",
        "Butcher" : "Guilds",
        "Journeyman" : "Guilds",
        "Merchant Guild" : "Guilds",
        "Soothsayer" : "Guilds",
        "Coin of the Realm" : "Adventures",
        "Page" : "Adventures",
        "Peasant" : "Adventures",
        "Ratcatcher" : "Adventures",
        "Raze" : "Adventures",
        "Amulet" : "Adventures",
        "Caravan Guard" : "Adventures",
        "Dungeon" : "Adventures",
        "Gear" : "Adventures",
        "Guide" : "Adventures",
        "Duplicate" : "Adventures",
        "Magpie" : "Adventures",
        "Messenger" : "Adventures",
        "Miser" : "Adventures",
        "Port" : "Adventures",
        "Ranger" : "Adventures",
        "Transmogrify" : "Adventures",
        "Artificer" : "Adventures",
        "Bridge Troll" : "Adventures",
        "Distant Lands" : "Adventures",
        "Giant" : "Adventures",
        "Haunted Woods" : "Adventures",
        "Lost City" : "Adventures",
        "Relic" : "Adventures",
        "Royal Carriage" : "Adventures",
        "Storyteller" : "Adventures",
        "Swamp Hag" : "Adventures",
        "Treasure Trove" : "Adventures",
        "Wine Merchant" : "Adventures",
        "Hireling" : "Adventures",
        "Alms" : "Adventures",
        "Borrow" : "Adventures",
        "Quest" : "Adventures",
        "Save" : "Adventures",
        "Scouting Party" : "Adventures",
        "Travelling Fair" : "Adventures",
        "Bonfire" : "Adventures",
        "Expedition" : "Adventures",
        "Ferry" : "Adventures",
        "Plan" : "Adventures",
        "Mission" : "Adventures",
        "Pilgrimage" : "Adventures",
        "Ball" : "Adventures",
        "Raid" : "Adventures",
        "Seaway" : "Adventures",
        "Trade" : "Adventures",
        "Lost Arts" : "Adventures",
        "Training" : "Adventures",
        "Inheritance" : "Adventures",
        "Pathfinding" : "Adventures",
        "Soldier" : "Adventures",
        "Fugitive" : "Adventures",
        "Disciple" : "Adventures",
        "Teacher" : "Adventures",
        "Treasure Hunter" : "Adventures",
        "Warrior" : "Adventures",
        "Hero" : "Adventures",
        "Champion" : "Adventures",
        "Plunder" : "Empires",
        "Encampment" : "Empires",
        "Emporium" : "Empires",
        "Patrician" : "Empires",
        "Bustling Village" : "Empires",
        "Settlers" : "Empires",
        "Rocks" : "Empires",
        "Catapult" : "Empires",
        "Fortune" : "Empires",
        "Gladiator" : "Empires",
        "Engineer" : "Empires",
        "City Quarter" : "Empires",
        "Royal Blacksmith" : "Empires",
        "Overlord" : "Empires",
        "Encampment" : "Empires",
        "Patrician" : "Empires",
        "Settlers" : "Empires",
        "Catapult" : "Empires",
        "Chariot Race" : "Empires",
        "Enchantress" : "Empires",
        "Farmers' Market" : "Empires",
        "Gladiator" : "Empires",
        "Rocks" : "Empires",
        "Sacrifice" : "Empires",
        "Temple" : "Empires",
        "Villa" : "Empires",
        "Archive" : "Empires",
        "Bustling Village" : "Empires",
        "Capital" : "Empires",
        "Charm" : "Empires",
        "Crown" : "Empires",
        "Emporium" : "Empires",
        "Forum" : "Empires",
        "Groundskeeper" : "Empires",
        "Legionary" : "Empires",
        "Plunder" : "Empires",
        "Wild Hunt" : "Empires",
        "Fortune" : "Empires",
        "Castles" : "Empires",
        "Humble Castle" : "Empires",
        "Crumbling Castle" : "Empires",
        "Small Castle" : "Empires",
        "Haunted Castle" : "Empires",
        "Opulent Castle" : "Empires",
        "Sprawling Castle" : "Empires",
        "Grand Castle" : "Empires",
        "King's Castle" : "Empires",
        "Triumph" : "Empires",
        "Annex" : "Empires",
        "Donate" : "Empires",
        "Advance" : "Empires",
        "Delve" : "Empires",
        "Tax" : "Empires",
        "Banquet" : "Empires",
        "Ritual" : "Empires",
        "Salt the Earth" : "Empires",
        "Wedding" : "Empires",
        "Windfall" : "Empires",
        "Conquest" : "Empires",
        "Dominate" : "Empires",
        "Aqueduct" : "Empires",
        "Arena" : "Empires",
        "Bandit Fort" : "Empires",
        "Basilica" : "Empires",
        "Battlefield" : "Empires",
        "Baths" : "Empires",
        "Colonnade" : "Empires",
        "Defiled Shrine" : "Empires",
        "Fountain" : "Empires",
        "Keep" : "Empires",
        "Labyrinth" : "Empires",
        "Mountain Pass" : "Empires",
        "Museum" : "Empires",
        "Obelisk" : "Empires",
        "Orchard" : "Empires",
        "Palace" : "Empires",
        "Tomb" : "Empires",
        "Tower" : "Empires",
        "Triumphal Arch" : "Empires",
        "Wall" : "Empires",
        "Wolf Den" : "Empires",
        "Druid" :	"Nocturne",
        "Faithful Hound" :	"Nocturne",
        "Guardian" :	"Nocturne",
        "Monastery" :	"Nocturne",
        "Pixie" :	"Nocturne",
        "Tracker" :	"Nocturne",
        "Changeling" :	"Nocturne",
        "Fool" :	"Nocturne",
        "Ghost Town" :	"Nocturne",
        "Leprechaun" :	"Nocturne",
        "Night Watchman" :	"Nocturne",
        "Secret Cave" :	"Nocturne",
        "Bard" :	"Nocturne",
        "Blessed Village" :	"Nocturne",
        "Cemetery" :	"Nocturne",
        "Conclave" :	"Nocturne",
        "Devil's Workshop" :	"Nocturne",
        "Exorcist" :	"Nocturne",
        "Necromancer" :	"Nocturne",
        "Shepherd" :	"Nocturne",
        "Skulk" :	"Nocturne",
        "Cobbler" :	"Nocturne",
        "Crypt" :	"Nocturne",
        "Cursed Village" :	"Nocturne",
        "Den of Sin" :	"Nocturne",
        "Idol" :	"Nocturne",
        "Pooka" :	"Nocturne",
        "Sacred Grove" :	"Nocturne",
        "Tormentor" :	"Nocturne",
        "Tragic Hero" :	"Nocturne",
        "Vampire" :	"Nocturne",
        "Werewolf" :	"Nocturne",
        "Raider" :	"Nocturne",
        "Will-o'-Wisp" :	"Nocturne",
        "Wish" :	"Nocturne",
        "Bat" :	"Nocturne",
        "Imp" :	"Nocturne",
        "Ghost" :	"Nocturne",
        "Zombie Apprentice" :	"Nocturne",
        "Zombie Mason" :	"Nocturne",
        "Zombie Spy" :	"Nocturne",
        "Haunted Mirror" :	"Nocturne",
        "Magic Lamp" :	"Nocturne",
        "Goat" :	"Nocturne",
        "Pasture" :	"Nocturne",
        "Pouch" :	"Nocturne",
        "Cursed Gold" :	"Nocturne",
        "Lucky Coin" :	"Nocturne",
        "The Earth's Gift" :	"Nocturne",
        "The Field's Gift" :	"Nocturne",
        "The Flame's Gift" :	"Nocturne",
        "The Forest's Gift" :	"Nocturne",
        "The Moon's Gift" :	"Nocturne",
        "The Mountain's Gift" :	"Nocturne",
        "The River's Gift" :	"Nocturne",
        "The Sea's Gift" :	"Nocturne",
        "The Sky's Gift" :	"Nocturne",
        "The Sun's Gift" :	"Nocturne",
        "The Swamp's Gift" :	"Nocturne",
        "The Wind's Gift" :	"Nocturne",
        "Bad Omens" :	"Nocturne",
        "Delusion" :	"Nocturne",
        "Envy" :	"Nocturne",
        "Famine" :	"Nocturne",
        "Fear" :	"Nocturne",
        "Greed" :	"Nocturne",
        "Haunting" :	"Nocturne",
        "Locusts" :	"Nocturne",
        "Misery" :	"Nocturne",
        "Plague" :	"Nocturne",
        "Poverty" :	"Nocturne",
        "War" :	"Nocturne",
        "Deluded" :	"Nocturne",
        "Envious" :	"Nocturne",
        "Lost in the Woods" :	"Nocturne",
        "Miserable" :	"Nocturne",
        "Twice Miserable" :	"Nocturne",
        "Border Guard" :	"Renaissance",
        "Ducat" :	"Renaissance",
        "Lackeys" :	"Renaissance",
        "Acting Troupe" :	"Renaissance",
        "Cargo Ship" :	"Renaissance",
        "Experiment" :	"Renaissance",
        "Improve" :	"Renaissance",
        "Flag Bearer" :	"Renaissance",
        "Hideout" :	"Renaissance",
        "Inventor" :	"Renaissance",
        "Mountain Village" :	"Renaissance",
        "Patron" :	"Renaissance",
        "Priest" :	"Renaissance",
        "Research" :	"Renaissance",
        "Silk Merchant" :	"Renaissance",
        "Old Witch" :	"Renaissance",
        "Recruiter" :	"Renaissance",
        "Scepter" :	"Renaissance",
        "Scholar" :	"Renaissance",
        "Sculptor" :	"Renaissance",
        "Seer" :	"Renaissance",
        "Spices" :	"Renaissance",
        "Swashbuckler" :	"Renaissance",
        "Treasurer" :	"Renaissance",
        "Villain" :	"Renaissance",
        "Flag" :	"Renaissance",
        "Horn" :	"Renaissance",
        "Key" :	"Renaissance",
        "Lantern" :	"Renaissance",
        "Treasure Chest" :	"Renaissance",
        "Cathedral" :	"Renaissance",
        "City Gate" :	"Renaissance",
        "Pageant" :	"Renaissance",
        "Sewers" :	"Renaissance",
        "Star Chart" :	"Renaissance",
        "Exploration" :	"Renaissance",
        "Fair" :	"Renaissance",
        "Silos" :	"Renaissance",
        "Sinister Plot" :	"Renaissance",
        "Academy" :	"Renaissance",
        "Capitalism" :	"Renaissance",
        "Fleet" :	"Renaissance",
        "Guildhall" :	"Renaissance",
        "Piazza" :	"Renaissance",
        "Road Network" :	"Renaissance",
        "Barracks" :	"Renaissance",
        "Crop Rotation" :	"Renaissance",
        "Innovation" :	"Renaissance",
        "Canal" :	"Renaissance",
        "Citadel" :	"Renaissance",
        "Black Cat" :	"Menagerie",
        "Sleigh" :	"Menagerie",
        "Supplies" :	"Menagerie",
        "Horse" :	"Menagerie",
        "Camel Train" :	"Menagerie",
        "Goatherd" :	"Menagerie",
        "Scrap" :	"Menagerie",
        "Sheepdog" :	"Menagerie",
        "Snowy Village" :	"Menagerie",
        "Stockpile" :	"Menagerie",
        "Bounty Hunter" :	"Menagerie",
        "Cardinal" :	"Menagerie",
        "Cavalry" :	"Menagerie",
        "Groom" :	"Menagerie",
        "Hostelry" :	"Menagerie",
        "Village Green" :	"Menagerie",
        "Fisherman" :	"Menagerie",
        "Hunting Lodge" :	"Menagerie",
        "Barge" :	"Menagerie",
        "Coven" :	"Menagerie",
        "Displace" :	"Menagerie",
        "Falconer" :	"Menagerie",
        "Gatekeeper" :	"Menagerie",
        "Kiln" :	"Menagerie",
        "Livery" :	"Menagerie",
        "Mastermind" :	"Menagerie",
        "Paddock" :	"Menagerie",
        "Sanctuary" :	"Menagerie",
        "Destrier" :	"Menagerie",
        "Wayfarer" :	"Menagerie",
        "Animal Fair" :	"Menagerie",
        "Delay" :	"Menagerie",
        "Desperation" :	"Menagerie",
        "Enhance" :	"Menagerie",
        "Gamble" :	"Menagerie",
        "Pursue" :	"Menagerie",
        "Ride" :	"Menagerie",
        "Toil" :	"Menagerie",
        "March" :	"Menagerie",
        "Transport" :	"Menagerie",
        "Banish" :	"Menagerie",
        "Bargain" :	"Menagerie",
        "Invest" :	"Menagerie",
        "Seize the Day" :	"Menagerie",
        "Commerce" :	"Menagerie",
        "Demand" :	"Menagerie",
        "Stampede" :	"Menagerie",
        "Reap" :	"Menagerie",
        "Enclave" :	"Menagerie",
        "Alliance" :	"Menagerie",
        "Populate" :	"Menagerie",
        "Way of the Butterfly" :	"Menagerie",
        "Way of the Camel" :	"Menagerie",
        "Way of the Chameleon" :	"Menagerie",
        "Way of the Frog" :	"Menagerie",
        "Way of the Goat" :	"Menagerie",
        "Way of the Horse" :	"Menagerie",
        "Way of the Mole" :	"Menagerie",
        "Way of the Monkey" :	"Menagerie",
        "Way of the Mouse" :	"Menagerie",
        "Way of the Mule" :	"Menagerie",
        "Way of the Otter" :	"Menagerie",
        "Way of the Ox" :	"Menagerie",
        "Way of the Owl" :	"Menagerie",
        "Way of the Pig" :	"Menagerie",
        "Way of the Rat" :	"Menagerie",
        "Way of the Seal" :	"Menagerie",
        "Way of the Sheep" :	"Menagerie",
        "Way of the Squirrel" :	"Menagerie",
        "Way of the Turtle" :	"Menagerie",
        "Way of the Worm" :	"Menagerie",
        "Sauna" : "Promos",
        "Avanto" : "Promos",
        "Black Market" : "Promos",
        "Envoy" : "Promos",
        "Sauna" : "Promos",
        "Walled Village" : "Promos",
        "Avanto" : "Promos",
        "Governor" : "Promos",
        "Stash" : "Promos",
        "Summon" : "Promos",
        "Prince" : "Promos"
    };

    if (card_name in card_set){
        return card_set[card_name];
    }
    return "";
}
