function get_card_set(card_name){
    var card_set = {
        "Cellar" : "Base",
        "Chapel" : "Base",
        "Moat" : "Base",
        "Chancellor" : "Base",
        "Harbinger" : "Base",
        "Merchant" : "Base",
        "Village" : "Base",
        "Woodcutter" : "Base",
        "Workshop" : "Base",
        "Vassal" : "Base",
        "Bureaucrat" : "Base",
        "Feast" : "Base",
        "Gardens" : "Base",
        "Militia" : "Base",
        "Moneylender" : "Base",
        "Poacher" : "Base",
        "Remodel" : "Base",
        "Smithy" : "Base",
        "Spy" : "Base",
        "Thief" : "Base",
        "Throne Room" : "Base",
        "Bandit" : "Base",
        "Council Room" : "Base",
        "Festival" : "Base",
        "Laboratory" : "Base",
        "Library" : "Base",
        "Market" : "Base",
        "Mine" : "Base",
        "Sentry" : "Base",
        "Witch" : "Base",
        "Adventurer" : "Base",
        "Artisan" : "Base",
        "Copper" : "Base",
        "Silver" : "Base",
        "Gold" : "Base",
        "Estate" : "Base",
        "Duchy" : "Base",
        "Province" : "Base",
        "Curse" : "Base",
        "Courtyard" : "Intrigue",
        "Lurker" : "Intrigue",
        "Pawn" : "Intrigue",
        "Secret Chamber" : "Intrigue",
        "Great Hall" : "Intrigue",
        "Masquerade" : "Intrigue",
        "Shanty Town" : "Intrigue",
        "Steward" : "Intrigue",
        "Swindler" : "Intrigue",
        "Wishing Well" : "Intrigue",
        "Baron" : "Intrigue",
        "Bridge" : "Intrigue",
        "Conspirator" : "Intrigue",
        "Coppersmith" : "Intrigue",
        "Diplomat" : "Intrigue",
        "Ironworks" : "Intrigue",
        "Mill" : "Intrigue",
        "Mining Village" : "Intrigue",
        "Scout" : "Intrigue",
        "Secret Passage" : "Intrigue",
        "Courtier" : "Intrigue",
        "Duke" : "Intrigue",
        "Minion" : "Intrigue",
        "Patrol" : "Intrigue",
        "Replace" : "Intrigue",
        "Saboteur" : "Intrigue",
        "Torturer" : "Intrigue",
        "Trading Post" : "Intrigue",
        "Tribute" : "Intrigue",
        "Upgrade" : "Intrigue",
        "Harem" : "Intrigue",
        "Nobles" : "Intrigue",
        "Embargo" : "Seaside",
        "Haven" : "Seaside",
        "Lighthouse" : "Seaside",
        "Native Village" : "Seaside",
        "Pearl Diver" : "Seaside",
        "Ambassador" : "Seaside",
        "Fishing Village" : "Seaside",
        "Lookout" : "Seaside",
        "Smugglers" : "Seaside",
        "Warehouse" : "Seaside",
        "Caravan" : "Seaside",
        "Cutpurse" : "Seaside",
        "Island" : "Seaside",
        "Navigator" : "Seaside",
        "Pirate Ship" : "Seaside",
        "Salvager" : "Seaside",
        "Sea Hag" : "Seaside",
        "Treasure Map" : "Seaside",
        "Bazaar" : "Seaside",
        "Explorer" : "Seaside",
        "Ghost Ship" : "Seaside",
        "Merchant Ship" : "Seaside",
        "Outpost" : "Seaside",
        "Tactician" : "Seaside",
        "Treasury" : "Seaside",
        "Wharf" : "Seaside",
        "Herbalist" : "Alchemy",
        "Potion" : "Alchemy",
        "Apprentice" : "Alchemy",
        "Transmute" : "Alchemy",
        "Vineyard" : "Alchemy",
        "Apothecary" : "Alchemy",
        "Scrying Pool" : "Alchemy",
        "University" : "Alchemy",
        "Alchemist" : "Alchemy",
        "Familiar" : "Alchemy",
        "Philosopher's Stone" : "Alchemy",
        "Golem" : "Alchemy",
        "Possession" : "Alchemy",
        "Loan" : "Prosperity",
        "Trade Route" : "Prosperity",
        "Watchtower" : "Prosperity",
        "Bishop" : "Prosperity",
        "Monument" : "Prosperity",
        "Quarry" : "Prosperity",
        "Talisman" : "Prosperity",
        "Worker's Village" : "Prosperity",
        "City" : "Prosperity",
        "Contraband" : "Prosperity",
        "Counting House" : "Prosperity",
        "Mint" : "Prosperity",
        "Mountebank" : "Prosperity",
        "Rabble" : "Prosperity",
        "Royal Seal" : "Prosperity",
        "Vault" : "Prosperity",
        "Venture" : "Prosperity",
        "Goons" : "Prosperity",
        "Grand Market" : "Prosperity",
        "Hoard" : "Prosperity",
        "Bank" : "Prosperity",
        "Expand" : "Prosperity",
        "Forge" : "Prosperity",
        "King's Court" : "Prosperity",
        "Peddler" : "Prosperity",
        "Platinum" : "Prosperity",
        "Colony" : "Prosperity",
        "Hamlet" : "Cornucopia",
        "Fortune Teller" : "Cornucopia",
        "Menagerie" : "Cornucopia",
        "Farming Village" : "Cornucopia",
        "Horse Traders" : "Cornucopia",
        "Remake" : "Cornucopia",
        "Tournament" : "Cornucopia",
        "Young Witch" : "Cornucopia",
        "Harvest" : "Cornucopia",
        "Horn of Plenty" : "Cornucopia",
        "Hunting Party" : "Cornucopia",
        "Jester" : "Cornucopia",
        "Fairgrounds" : "Cornucopia",
        "Bag of Gold" : "Cornucopia",
        "Diadem" : "Cornucopia",
        "Followers" : "Cornucopia",
        "Princess" : "Cornucopia",
        "Trusty Steed" : "Cornucopia",
        "Crossroads" : "Hinterlands",
        "Duchess" : "Hinterlands",
        "Fool's Gold" : "Hinterlands",
        "Develop" : "Hinterlands",
        "Oasis" : "Hinterlands",
        "Oracle" : "Hinterlands",
        "Scheme" : "Hinterlands",
        "Tunnel" : "Hinterlands",
        "Jack of all Trades" : "Hinterlands",
        "Noble Brigand" : "Hinterlands",
        "Nomad Camp" : "Hinterlands",
        "Silk Road" : "Hinterlands",
        "Spice Merchant" : "Hinterlands",
        "Trader" : "Hinterlands",
        "Cache" : "Hinterlands",
        "Cartographer" : "Hinterlands",
        "Embassy" : "Hinterlands",
        "Haggler" : "Hinterlands",
        "Highway" : "Hinterlands",
        "Ill-Gotten Gains" : "Hinterlands",
        "Inn" : "Hinterlands",
        "Mandarin" : "Hinterlands",
        "Margrave" : "Hinterlands",
        "Stables" : "Hinterlands",
        "Border Village" : "Hinterlands",
        "Farmland" : "Hinterlands",
        "Madman" : "Dark Ages",
        "Mercenary" : "Dark Ages",
        "Spoils" : "Dark Ages",
        "Poor House" : "Dark Ages",
        "Beggar" : "Dark Ages",
        "Squire" : "Dark Ages",
        "Vagrant" : "Dark Ages",
        "Forager" : "Dark Ages",
        "Hermit" : "Dark Ages",
        "Market Square" : "Dark Ages",
        "Sage" : "Dark Ages",
        "Storeroom" : "Dark Ages",
        "Urchin" : "Dark Ages",
        "Armory" : "Dark Ages",
        "Death Cart" : "Dark Ages",
        "Feodum" : "Dark Ages",
        "Fortress" : "Dark Ages",
        "Ironmonger" : "Dark Ages",
        "Marauder" : "Dark Ages",
        "Procession" : "Dark Ages",
        "Rats" : "Dark Ages",
        "Scavenger" : "Dark Ages",
        "Wandering Minstrel" : "Dark Ages",
        "Band of Misfits" : "Dark Ages",
        "Bandit Camp" : "Dark Ages",
        "Catacombs" : "Dark Ages",
        "Count" : "Dark Ages",
        "Counterfeit" : "Dark Ages",
        "Cultist" : "Dark Ages",
        "Graverobber" : "Dark Ages",
        "Junk Dealer" : "Dark Ages",
        "Mystic" : "Dark Ages",
        "Pillage" : "Dark Ages",
        "Rebuild" : "Dark Ages",
        "Rogue" : "Dark Ages",
        "Altar" : "Dark Ages",
        "Hunting Grounds" : "Dark Ages",
        "Ruins" : "Dark Ages",
        "Abandoned Mine" : "Dark Ages",
        "Ruined Library" : "Dark Ages",
        "Ruined Market" : "Dark Ages",
        "Ruined Village" : "Dark Ages",
        "Survivors" : "Dark Ages",
        "Knights" : "Dark Ages",
        "Dame Anna" : "Dark Ages",
        "Dame Josephine" : "Dark Ages",
        "Dame Molly" : "Dark Ages",
        "Dame Natalie" : "Dark Ages",
        "Dame Sylvia" : "Dark Ages",
        "Sir Bailey" : "Dark Ages",
        "Sir Destry" : "Dark Ages",
        "Sir Martin" : "Dark Ages",
        "Sir Michael" : "Dark Ages",
        "Sir Vander" : "Dark Ages",
        "Shelters" : "Dark Ages",
        "Hovel" : "Dark Ages",
        "Necropolis" : "Dark Ages",
        "Overgrown Estate" : "Dark Ages",
        "Candlestick Maker" : "Guilds",
        "Stonemason" : "Guilds",
        "Doctor" : "Guilds",
        "Masterpiece" : "Guilds",
        "Advisor" : "Guilds",
        "Herald" : "Guilds",
        "Plaza" : "Guilds",
        "Taxman" : "Guilds",
        "Baker" : "Guilds",
        "Butcher" : "Guilds",
        "Journeyman" : "Guilds",
        "Merchant Guild" : "Guilds",
        "Soothsayer" : "Guilds",
        "Coin of the Realm" : "Adventures",
        "Page" : "Adventures",
        "Peasant" : "Adventures",
        "Ratcatcher" : "Adventures",
        "Raze" : "Adventures",
        "Amulet" : "Adventures",
        "Caravan Guard" : "Adventures",
        "Dungeon" : "Adventures",
        "Gear" : "Adventures",
        "Guide" : "Adventures",
        "Duplicate" : "Adventures",
        "Magpie" : "Adventures",
        "Messenger" : "Adventures",
        "Miser" : "Adventures",
        "Port" : "Adventures",
        "Ranger" : "Adventures",
        "Transmogrify" : "Adventures",
        "Artificer" : "Adventures",
        "Bridge Troll" : "Adventures",
        "Distant Lands" : "Adventures",
        "Giant" : "Adventures",
        "Haunted Woods" : "Adventures",
        "Lost City" : "Adventures",
        "Relic" : "Adventures",
        "Royal Carriage" : "Adventures",
        "Storyteller" : "Adventures",
        "Swamp Hag" : "Adventures",
        "Treasure Trove" : "Adventures",
        "Wine Merchant" : "Adventures",
        "Hireling" : "Adventures",
        "Alms" : "Adventures",
        "Borrow" : "Adventures",
        "Quest" : "Adventures",
        "Save" : "Adventures",
        "Scouting Party" : "Adventures",
        "Travelling Fair" : "Adventures",
        "Bonfire" : "Adventures",
        "Expedition" : "Adventures",
        "Ferry" : "Adventures",
        "Plan" : "Adventures",
        "Mission" : "Adventures",
        "Pilgrimage" : "Adventures",
        "Ball" : "Adventures",
        "Raid" : "Adventures",
        "Seaway" : "Adventures",
        "Trade" : "Adventures",
        "Lost Arts" : "Adventures",
        "Training" : "Adventures",
        "Inheritance" : "Adventures",
        "Pathfinding" : "Adventures",
        "Soldier" : "Adventures",
        "Fugitive" : "Adventures",
        "Disciple" : "Adventures",
        "Teacher" : "Adventures",
        "Treasure Hunter" : "Adventures",
        "Warrior" : "Adventures",
        "Hero" : "Adventures",
        "Champion" : "Adventures",
        "Plunder" : "Empires",
        "Encampment" : "Empires",
        "Emporium" : "Empires",
        "Patrician" : "Empires",
        "Bustling Village" : "Empires",
        "Settlers" : "Empires",
        "Rocks" : "Empires",
        "Catapult" : "Empires",
        "Fortune" : "Empires",
        "Gladiator" : "Empires",
        "Engineer" : "Empires",
        "City Quarter" : "Empires",
        "Royal Blacksmith" : "Empires",
        "Overlord" : "Empires",
        "Encampment" : "Empires",
        "Patrician" : "Empires",
        "Settlers" : "Empires",
        "Catapult" : "Empires",
        "Chariot Race" : "Empires",
        "Enchantress" : "Empires",
        "Farmers' Market" : "Empires",
        "Gladiator" : "Empires",
        "Rocks" : "Empires",
        "Sacrifice" : "Empires",
        "Temple" : "Empires",
        "Villa" : "Empires",
        "Archive" : "Empires",
        "Bustling Village" : "Empires",
        "Capital" : "Empires",
        "Charm" : "Empires",
        "Crown" : "Empires",
        "Emporium" : "Empires",
        "Forum" : "Empires",
        "Groundskeeper" : "Empires",
        "Legionary" : "Empires",
        "Plunder" : "Empires",
        "Wild Hunt" : "Empires",
        "Fortune" : "Empires",
        "Castles" : "Empires",
        "Humble Castle" : "Empires",
        "Crumbling Castle" : "Empires",
        "Small Castle" : "Empires",
        "Haunted Castle" : "Empires",
        "Opulent Castle" : "Empires",
        "Sprawling Castle" : "Empires",
        "Grand Castle" : "Empires",
        "King's Castle" : "Empires",
        "Triumph" : "Empires",
        "Annex" : "Empires",
        "Donate" : "Empires",
        "Advance" : "Empires",
        "Delve" : "Empires",
        "Tax" : "Empires",
        "Banquet" : "Empires",
        "Ritual" : "Empires",
        "Salt the Earth" : "Empires",
        "Wedding" : "Empires",
        "Windfall" : "Empires",
        "Conquest" : "Empires",
        "Dominate" : "Empires",
        "Aqueduct" : "Empires",
        "Arena" : "Empires",
        "Bandit Fort" : "Empires",
        "Basilica" : "Empires",
        "Battlefield" : "Empires",
        "Baths" : "Empires",
        "Colonnade" : "Empires",
        "Defiled Shrine" : "Empires",
        "Fountain" : "Empires",
        "Keep" : "Empires",
        "Labyrinth" : "Empires",
        "Mountain Pass" : "Empires",
        "Museum" : "Empires",
        "Obelisk" : "Empires",
        "Orchard" : "Empires",
        "Palace" : "Empires",
        "Tomb" : "Empires",
        "Tower" : "Empires",
        "Triumphal Arch" : "Empires",
        "Wall" : "Empires",
        "Wolf Den" : "Empires",
        "Sauna" : "Promos",
        "Avanto" : "Promos",
        "Black Market" : "Promos",
        "Envoy" : "Promos",
        "Sauna" : "Promos",
        "Walled Village" : "Promos",
        "Avanto" : "Promos",
        "Governor" : "Promos",
        "Stash" : "Promos",
        "Summon" : "Promos",
        "Prince" : "Promos"
    };

    if (card_name in card_set){
        return card_set[card_name];
    }
    return "";
}